# Generated by Django 4.2.4 on 2024-04-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(null=True, upload_to='static/questions/'),
        ),
        migrations.AddField(
            model_name='test',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
