# Generated by Django 4.2.4 on 2024-04-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_test_image_test_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='no_of_ques',
        ),
    ]
